

CREATE TABLE USERS
(
    USERID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    ROLE NVARCHAR(255) NOT NULL,
    R_QUESTION NVARCHAR(255),
    R_ANSWER NVARCHAR(255)
);

DROP TABLE USERS

-- Insert data into the USERS table
SELECT * FROM USERS;
